sudo: required
services:
  - docker

before_install:
  - docker build -t fabiojfl/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fabiojfl/react-test npm test

after_success:
  - docker build -t fabiojfl/multi-client ./client
  - docker build -t fabiojfl/multi-nginx ./nginx
  - docker build -t fabiojfl/multi-server ./server
  - docker build -t fabiojfl/multi-worker ./worker
  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to Docker Hub
  - docker push fabiojfl/multi-client
  - docker push fabiojfl/multi-nginx
  - docker push fabiojfl/multi-server
  - docker push fabiojfl/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multidocker-env-1'
  bucket_name: 'elasticbeanstalk-us-east-2-876424347093'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY